[workspace]
authors = ["* <*@outlook.com>"]
channels = ["conda-forge"]
name = "lab"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12"

[dependencies]

[feature.t.dependencies]
tensorflow = ">=1.14.0,<2"
matplotlib = ">=3.5.3,<4"
numpy = ">=1.21.6,<2"
scipy = ">=1.7.3,<2"
h5py = ">=3.7.0,<4"
pandas = ">=1.3.5,<2"


[feature.py312.dependencies]
python = "3.12.*"
scikit-learn = ">=1.7.2,<2"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"

[feature.pt.dependencies]
pytorch-gpu = "*"
torchvision = ">=0.24.1,<0.25"
tqdm = ">=4.67.1,<5"
matplotlib = ">=3.10.8,<4"
flask = ">=3.1.2,<4"
pillow = ">=12.0.0,<13"
pandas = ">=2.3.3,<3"
pytorch-msssim = ">=1.0.0,<2"

[environments]
default = ["py312"]
t = ["t"]
pt = ["pt"]
